name: Deploy Docs

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7.29.3

      - name: Set node version to 18.15.0
        uses: actions/setup-node@v3
        with:
          node-version: 18.15.0
          registry-url: https://registry.npmjs.org/
          cache: 'pnpm'

      - name: Install deps
        run: pnpm install

      - name: Build Docs
        run: pnpm run docs:build

      - name: Deploy Docs
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs-dist
