name: Deploy Docs

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
      - '@mango-kit/**' # Push events to matching @mango-kit*, i.e. @mango-kit@components

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.12.1

      - name: Set node version to 20.10.0
        uses: actions/setup-node@v3
        with:
          node-version: 20.10.0
          registry-url: https://registry.npmjs.org/
          cache: 'pnpm'

      - name: Install deps
        run: pnpm install

      - name: Build Docs
        run: pnpm run docs:build

      - name: Deploy Docs
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          publish_dir: ./docs-dist
